QINGPING_API_KEY = 'YOU_API_KEY_HERE'
QINGPING_API_SECRET = 'YOU_API_SECRET_HERE'

INFLUX_HOST = 'your.influx.host'
INFLUX_PORT = 3086
INFLUX_USERNAME = 'influx_user'
INFLUX_PASSWORD = 'influx_password'
INFLUX_DATABASE = 'influx_database'
INFLUX_MEASUREMENT = 'qingping'

POLL_INTERVAL = 30
